### PR TITLE
x11-drivers/nvidia-drivers:bump to 455.46.01-r1  due to a dependency conflict:x11-libs/gdk-pixbuf:2

### PR DESCRIPTION
**Pull request by hedmo**
nvidia_conflict

### CODE REVIEW

**Comment by kakra** [comment]
Did Gentoo drop the flag?

**Comment by hedmo** [comment]
Yes they have: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=6158cd122253e1e75132083031e72cd8158f0bd4

**Comment by hedmo** [comment]
BTW i did not manage to use repoman.some how when i was done i could not get out of nano.it was like i had 100 commits to deal with so i had to remove My fork and redo all again.maybe it has to DO with My key or something.

**Comment by kakra** [comment]
I hope you don't mind I completed the PR with a different approach. I've put a Co-authored tag.

**Pull request closed without merging**
