### PR TITLE
x11-drivers/nvidia-drivers: removal of nvidia-driver.eclass

### PR DESCRIPTION
**Pull request by hedmo**
Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Andreas Westman Dorcsak <hedmoo@yahoo.com>

### CODE REVIEW

**Comment by hedmo** [comment]
gentoo has droped the nvidia-driver.eclass....

gentoos inherit is :
desktop linux-info linux-mod multilib-build optfeature \	readme.gentoo-r1 systemd toolchain-funcs unpacker

ATM i have just removed the nvidia-driver.eclass and used repoman wich complained about :
DESCRIPTION.missing [fatal] 
HOMEPAGE.missing [fatal

**Comment by kakra** [comment]
I'm aware of that already and working on it. Apparently, it's not as simple as cherry picking some ebuild patches: The Gentoo ebuilds have a new maintainer now, and have been completely redone to fix some long standing issues.

**Comment by hedmo** [comment]
> I'm aware of that already and working on it. Apparently, it's not as simple as cherry picking some ebuild patches: 

you are right . the ebuilds needs to be fixed.

> The Gentoo ebuilds have a new maintainer now, and have been completely redone to fix some long standing issues.

hope you can use some of that ebuilds to make it more easy.

**Comment by kakra** [comment]
It would be easy if repoman wouldn't insist on having the missing eclass for those unchanged ebuilds...

**Comment by hedmo** [comment]
have you tested the ebuilds? as gentoo has removed the eclass i dont think they work . you can add the eclass to your overlay if you want but that is like going backwords ...

**Comment by kakra** [comment]
I've pushed a temporary fix to work around the issue. I'm going to first update my kernel to the new version with the old eclass-based ebuilds first before taking care of it. This also works around the repoman issue until I can finally also drop the eclass.

**Comment by kakra** [comment]
I'm going to slowly deprecate the eclass, not touching most of the old ebuilds but dropping them when new ebuilds arrive. Do you need any particular version except the newest?

**Comment by hedmo** [comment]
> I'm going to slowly deprecate the eclass, not touching most of the old ebuilds but dropping them when new ebuilds arrive. Do you need any particular version except the newest?

no . i have a rtx2060 so i am fine with >newest :) . i had a look  at the eclass and i think it is quite simple to adapt it to the ebuilds . if you like i can check it out and try to adapt it for you ?

**Comment by kakra** [comment]
Give me some minutes to check out my latest changes for 455.50.19-r1, I'll push them soon, then adapt it to the other 455.50 ebuilds. If you like, you can adapt and test the older ebuilds in a new PR then. We could get rid of all the left over repoman warnings that way.

**Comment by kakra** [comment]
In any case we'd need revbumps so drivers become picked up for rebuild by portage. The -rXYY ebuilds would need to increase the X digit because YY is used it get the patch version of the beta driver (it was a work-around no longer needed but we cannot bump down from `AAA.BB-rXYY` or `AAA.BB.YY-r(X+1)`).

**Comment by hedmo** [comment]
okej i will wait for your cleanup and checkout gentoos ebuilds to see what is going on :)

**Comment by kakra** [comment]
I've done the 455.50 branch. All touched ebuilds were compile/install-tested with
```
sudo ebuild nvidia-drivers-VERSION.ebuild clean install
```

and I'm currently running the latest one, so it was merged and boot-tested.

If you like, you can go on from here. It may take a bit more effort to check the ebuilds which still depend on eselect-opengl, I'd recommend to actually merge those and test if the system still runs.

Or we ignore those, and phase them out slowly when new drivers appear. My current policy is to keep the latest three ebuilds of each version XXX.YY.ZZ, XXX.YY and XXX. So if we get a vulkan beta driver version higher than 455, I would remove 440.66.17 and also drop 455.50.12 and 455.50.14 as of commit f78fe386e7c1bc9ed326a2176fe1fae661c33c1f.

**Pull request closed without merging**
